version: '2'

services:
  nginx:
    container_name: forest-nginx-lb
    build: ./nginx
    links:
      - app-1:app-1
      - app-2:app-2
      - app-3:app-3
    ports:
      - 4000:80
    depends_on:
      - app-1
      - app-2
      - app-3

  app-1:
    container_name: forest-nodejs-1
    # build: .
    image: registry.gitlab.com/sukso96100/forest-nodejs:latest
    ports:
      - 3000

  app-2:
    container_name: forest-nodejs-2
    # build: .
    image: registry.gitlab.com/sukso96100/forest-nodejs:latest
    ports:
      - 3000

  app-3:
    container_name: forest-nodejs-3
    # build: .
    image: registry.gitlab.com/sukso96100/forest-nodejs:latest
    ports:
      - 3000
