version: '2'

services:
  nginx:
    container_name: forest-nginx-lb
    build: ./nginx
    environment:
      - SERVER_DOMAIN=f.youngbin.xyz
      - SERVER_EMAIL=we.sss.you@gmail.com
    links:
      - app-1:app-1
      - app-2:app-2
      - app-3:app-3
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-1
      - app-2
      - app-3

  app-1:
    container_name: forest-nodejs-1
    image: registry.gitlab.com/sukso96100/forest-nodejs:latest
    ports:
      - 3000

  app-2:
    container_name: forest-nodejs-2
    build: .
    ports:
      - 3000

  app-3:
    container_name: forest-nodejs-3
    build: .
    ports:
      - 3000
